# coding: utf-8

"""
    NBA v3 Scores

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_scores
from sportsdata.nba_scores.models.nba_scores_team import NbaScoresTeam  # noqa: E501
from sportsdata.nba_scores.rest import ApiException


class TestNbaScoresTeam(unittest.TestCase):
    """NbaScoresTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaScoresTeam(self):
        """Test NbaScoresTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_scores.models.nba_scores_team.NbaScoresTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
