# coding: utf-8

"""
    NHL v3 Play-by-Play

    NHL play-by-play API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nhl_play_by_play
from sportsdata.nhl_play_by_play.models.nhl_play_by_play_scoring_play import NhlPlayByPlayScoringPlay  # noqa: E501
from sportsdata.nhl_play_by_play.rest import ApiException


class TestNhlPlayByPlayScoringPlay(unittest.TestCase):
    """NhlPlayByPlayScoringPlay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNhlPlayByPlayScoringPlay(self):
        """Test NhlPlayByPlayScoringPlay"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nhl_play_by_play.models.nhl_play_by_play_scoring_play.NhlPlayByPlayScoringPlay()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
