# coding: utf-8

"""
    NHL v3 Projections

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nhl_projections
from sportsdata.nhl_projections.models.nhl_projections_period import NhlProjectionsPeriod  # noqa: E501
from sportsdata.nhl_projections.rest import ApiException


class TestNhlProjectionsPeriod(unittest.TestCase):
    """NhlProjectionsPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNhlProjectionsPeriod(self):
        """Test NhlProjectionsPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nhl_projections.models.nhl_projections_period.NhlProjectionsPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
