# coding: utf-8

"""
    NHL v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nhl_odds
from sportsdata.nhl_odds.models.nhl_odds_betting_market import NhlOddsBettingMarket  # noqa: E501
from sportsdata.nhl_odds.rest import ApiException


class TestNhlOddsBettingMarket(unittest.TestCase):
    """NhlOddsBettingMarket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNhlOddsBettingMarket(self):
        """Test NhlOddsBettingMarket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nhl_odds.models.nhl_odds_betting_market.NhlOddsBettingMarket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
