# coding: utf-8

"""
    MLB v3 Play-by-Play

    MLB play-by-play API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.mlb_play_by_play
from sportsdata.mlb_play_by_play.models.mlb_play_by_play_series import MlbPlayByPlaySeries  # noqa: E501
from sportsdata.mlb_play_by_play.rest import ApiException


class TestMlbPlayByPlaySeries(unittest.TestCase):
    """MlbPlayByPlaySeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlbPlayByPlaySeries(self):
        """Test MlbPlayByPlaySeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.mlb_play_by_play.models.mlb_play_by_play_series.MlbPlayByPlaySeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
