# coding: utf-8

"""
    NFL v3 Advanced Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nfl_advanced_metrics
from sportsdata.nfl_advanced_metrics.models.nfl_advanced_metrics_advanced_player_medical import NflAdvancedMetricsAdvancedPlayerMedical  # noqa: E501
from sportsdata.nfl_advanced_metrics.rest import ApiException


class TestNflAdvancedMetricsAdvancedPlayerMedical(unittest.TestCase):
    """NflAdvancedMetricsAdvancedPlayerMedical unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNflAdvancedMetricsAdvancedPlayerMedical(self):
        """Test NflAdvancedMetricsAdvancedPlayerMedical"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nfl_advanced_metrics.models.nfl_advanced_metrics_advanced_player_medical.NflAdvancedMetricsAdvancedPlayerMedical()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
