# coding: utf-8

"""
    CS:GO v3 Scores

    CS:GO v3 Scores  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.csgo_scores
from sportsdata.csgo_scores.models.csgo_scores_round import CsgoScoresRound  # noqa: E501
from sportsdata.csgo_scores.rest import ApiException


class TestCsgoScoresRound(unittest.TestCase):
    """CsgoScoresRound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCsgoScoresRound(self):
        """Test CsgoScoresRound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.csgo_scores.models.csgo_scores_round.CsgoScoresRound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
