# coding: utf-8

"""
    NFL v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nfl_odds
from sportsdata.nfl_odds.models.nfl_odds_betting_market import NflOddsBettingMarket  # noqa: E501
from sportsdata.nfl_odds.rest import ApiException


class TestNflOddsBettingMarket(unittest.TestCase):
    """NflOddsBettingMarket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNflOddsBettingMarket(self):
        """Test NflOddsBettingMarket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nfl_odds.models.nfl_odds_betting_market.NflOddsBettingMarket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
