# coding: utf-8

"""
    CFB v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.cfb_odds
from sportsdata.cfb_odds.models.cfb_odds_betting_market_split import CfbOddsBettingMarketSplit  # noqa: E501
from sportsdata.cfb_odds.rest import ApiException


class TestCfbOddsBettingMarketSplit(unittest.TestCase):
    """CfbOddsBettingMarketSplit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCfbOddsBettingMarketSplit(self):
        """Test CfbOddsBettingMarketSplit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.cfb_odds.models.cfb_odds_betting_market_split.CfbOddsBettingMarketSplit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
