# coding: utf-8

"""
    MLB v3 Scores

    MLB scores API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.mlb_scores
from sportsdata.mlb_scores.models.mlb_scores_standing import MlbScoresStanding  # noqa: E501
from sportsdata.mlb_scores.rest import ApiException


class TestMlbScoresStanding(unittest.TestCase):
    """MlbScoresStanding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlbScoresStanding(self):
        """Test MlbScoresStanding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.mlb_scores.models.mlb_scores_standing.MlbScoresStanding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
