# coding: utf-8

"""
    MLB v3 Projections

    MLB projections API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.mlb_projections
from sportsdata.mlb_projections.models.mlb_projections_player_game_projection import MlbProjectionsPlayerGameProjection  # noqa: E501
from sportsdata.mlb_projections.rest import ApiException


class TestMlbProjectionsPlayerGameProjection(unittest.TestCase):
    """MlbProjectionsPlayerGameProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlbProjectionsPlayerGameProjection(self):
        """Test MlbProjectionsPlayerGameProjection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.mlb_projections.models.mlb_projections_player_game_projection.MlbProjectionsPlayerGameProjection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
