# coding: utf-8

"""
    Soccer v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.soccer_odds
from sportsdata.soccer_odds.models.soccer_odds_betting_entity_metadata_collection import SoccerOddsBettingEntityMetadataCollection  # noqa: E501
from sportsdata.soccer_odds.rest import ApiException


class TestSoccerOddsBettingEntityMetadataCollection(unittest.TestCase):
    """SoccerOddsBettingEntityMetadataCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoccerOddsBettingEntityMetadataCollection(self):
        """Test SoccerOddsBettingEntityMetadataCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.soccer_odds.models.soccer_odds_betting_entity_metadata_collection.SoccerOddsBettingEntityMetadataCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
