# coding: utf-8

"""
    CFB v3 Stats

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.cfb_stats
from sportsdata.cfb_stats.models.cfb_stats_season import CfbStatsSeason  # noqa: E501
from sportsdata.cfb_stats.rest import ApiException


class TestCfbStatsSeason(unittest.TestCase):
    """CfbStatsSeason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCfbStatsSeason(self):
        """Test CfbStatsSeason"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.cfb_stats.models.cfb_stats_season.CfbStatsSeason()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
