# coding: utf-8

"""
    NFL v3 Stats

    NFL rosters, player stats, team stats, and fantasy stats API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nfl_stats
from sportsdata.nfl_stats.models.nfl_stats_team import NflStatsTeam  # noqa: E501
from sportsdata.nfl_stats.rest import ApiException


class TestNflStatsTeam(unittest.TestCase):
    """NflStatsTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNflStatsTeam(self):
        """Test NflStatsTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nfl_stats.models.nfl_stats_team.NflStatsTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
