# coding: utf-8

"""
    Soccer v3 Projections

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.soccer_projections
from sportsdata.soccer_projections.models.soccer_projections_dfs_slate_game import SoccerProjectionsDfsSlateGame  # noqa: E501
from sportsdata.soccer_projections.rest import ApiException


class TestSoccerProjectionsDfsSlateGame(unittest.TestCase):
    """SoccerProjectionsDfsSlateGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoccerProjectionsDfsSlateGame(self):
        """Test SoccerProjectionsDfsSlateGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.soccer_projections.models.soccer_projections_dfs_slate_game.SoccerProjectionsDfsSlateGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
