# coding: utf-8

"""
    NBA v3 Stats

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_stats
from sportsdata.nba_stats.models.nba_stats_game import NbaStatsGame  # noqa: E501
from sportsdata.nba_stats.rest import ApiException


class TestNbaStatsGame(unittest.TestCase):
    """NbaStatsGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaStatsGame(self):
        """Test NbaStatsGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_stats.models.nba_stats_game.NbaStatsGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
