# coding: utf-8

"""
    Golf v3 Headshots

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.golf_headshots
from sportsdata.golf_headshots.models.golf_headshots_headshot import GolfHeadshotsHeadshot  # noqa: E501
from sportsdata.golf_headshots.rest import ApiException


class TestGolfHeadshotsHeadshot(unittest.TestCase):
    """GolfHeadshotsHeadshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGolfHeadshotsHeadshot(self):
        """Test GolfHeadshotsHeadshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.golf_headshots.models.golf_headshots_headshot.GolfHeadshotsHeadshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
