# coding: utf-8

"""
    MLB v3 Stats

    MLB scores, stats, and news API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.mlb_stats
from sportsdata.mlb_stats.models.mlb_stats_box_score import MlbStatsBoxScore  # noqa: E501
from sportsdata.mlb_stats.rest import ApiException


class TestMlbStatsBoxScore(unittest.TestCase):
    """MlbStatsBoxScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlbStatsBoxScore(self):
        """Test MlbStatsBoxScore"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.mlb_stats.models.mlb_stats_box_score.MlbStatsBoxScore()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
