# coding: utf-8

"""
    CBB v3 Scores

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.cbb_scores
from sportsdata.cbb_scores.models.cbb_scores_period import CbbScoresPeriod  # noqa: E501
from sportsdata.cbb_scores.rest import ApiException


class TestCbbScoresPeriod(unittest.TestCase):
    """CbbScoresPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCbbScoresPeriod(self):
        """Test CbbScoresPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.cbb_scores.models.cbb_scores_period.CbbScoresPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
