# coding: utf-8

"""
    NBA v3 Play-by-Play

    NBA play-by-play API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_play_by_play
from sportsdata.nba_play_by_play.models.nba_play_by_play_quarter import NbaPlayByPlayQuarter  # noqa: E501
from sportsdata.nba_play_by_play.rest import ApiException


class TestNbaPlayByPlayQuarter(unittest.TestCase):
    """NbaPlayByPlayQuarter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaPlayByPlayQuarter(self):
        """Test NbaPlayByPlayQuarter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_play_by_play.models.nba_play_by_play_quarter.NbaPlayByPlayQuarter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
