# coding: utf-8

"""
    NHL v3 Scores

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nhl_scores
from sportsdata.nhl_scores.models.nhl_scores_game import NhlScoresGame  # noqa: E501
from sportsdata.nhl_scores.rest import ApiException


class TestNhlScoresGame(unittest.TestCase):
    """NhlScoresGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNhlScoresGame(self):
        """Test NhlScoresGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nhl_scores.models.nhl_scores_game.NhlScoresGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
