# coding: utf-8

"""
    Soccer v3 Stats

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.soccer_stats
from sportsdata.soccer_stats.models.soccer_stats_competition_detail import SoccerStatsCompetitionDetail  # noqa: E501
from sportsdata.soccer_stats.rest import ApiException


class TestSoccerStatsCompetitionDetail(unittest.TestCase):
    """SoccerStatsCompetitionDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoccerStatsCompetitionDetail(self):
        """Test SoccerStatsCompetitionDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.soccer_stats.models.soccer_stats_competition_detail.SoccerStatsCompetitionDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
