# coding: utf-8

"""
    LoL v3 Stats

    LoL v3 Stats  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.lol_stats
from sportsdata.lol_stats.models.lol_stats_team_match import LolStatsTeamMatch  # noqa: E501
from sportsdata.lol_stats.rest import ApiException


class TestLolStatsTeamMatch(unittest.TestCase):
    """LolStatsTeamMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLolStatsTeamMatch(self):
        """Test LolStatsTeamMatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.lol_stats.models.lol_stats_team_match.LolStatsTeamMatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
