# coding: utf-8

"""
    Golf v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.golf_v2
from sportsdata.golf_v2.models.golf_v2_round import GolfV2Round  # noqa: E501
from sportsdata.golf_v2.rest import ApiException


class TestGolfV2Round(unittest.TestCase):
    """GolfV2Round unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGolfV2Round(self):
        """Test GolfV2Round"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.golf_v2.models.golf_v2_round.GolfV2Round()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
