# coding: utf-8

"""
    CFB v3 Scores

    CFB schedules, scores, team stats, odds, weather, and news API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.cfb_scores
from sportsdata.cfb_scores.models.cfb_scores_player import CfbScoresPlayer  # noqa: E501
from sportsdata.cfb_scores.rest import ApiException


class TestCfbScoresPlayer(unittest.TestCase):
    """CfbScoresPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCfbScoresPlayer(self):
        """Test CfbScoresPlayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.cfb_scores.models.cfb_scores_player.CfbScoresPlayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
