# coding: utf-8

"""
    Soccer v3 Scores

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.soccer_scores
from sportsdata.soccer_scores.models.soccer_scores_team_game import SoccerScoresTeamGame  # noqa: E501
from sportsdata.soccer_scores.rest import ApiException


class TestSoccerScoresTeamGame(unittest.TestCase):
    """SoccerScoresTeamGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoccerScoresTeamGame(self):
        """Test SoccerScoresTeamGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.soccer_scores.models.soccer_scores_team_game.SoccerScoresTeamGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
