# coding: utf-8

"""
    LoL v3 Scores

    LoL v3 Scores  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.lol_scores
from sportsdata.lol_scores.models.lol_scores_competition_detail import LolScoresCompetitionDetail  # noqa: E501
from sportsdata.lol_scores.rest import ApiException


class TestLolScoresCompetitionDetail(unittest.TestCase):
    """LolScoresCompetitionDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLolScoresCompetitionDetail(self):
        """Test LolScoresCompetitionDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.lol_scores.models.lol_scores_competition_detail.LolScoresCompetitionDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
