# coding: utf-8

"""
    MLB v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.mlb_odds
from sportsdata.mlb_odds.models.mlb_odds_game import MlbOddsGame  # noqa: E501
from sportsdata.mlb_odds.rest import ApiException


class TestMlbOddsGame(unittest.TestCase):
    """MlbOddsGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMlbOddsGame(self):
        """Test MlbOddsGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.mlb_odds.models.mlb_odds_game.MlbOddsGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
