# coding: utf-8

"""
    NFL v3 Scores

    NFL schedules, scores, odds, weather, and news API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nfl_scores
from sportsdata.nfl_scores.models.nfl_scores_timeframe import NflScoresTimeframe  # noqa: E501
from sportsdata.nfl_scores.rest import ApiException


class TestNflScoresTimeframe(unittest.TestCase):
    """NflScoresTimeframe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNflScoresTimeframe(self):
        """Test NflScoresTimeframe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nfl_scores.models.nfl_scores_timeframe.NflScoresTimeframe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
