# coding: utf-8

"""
    NBA v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_odds
from sportsdata.nba_odds.models.nba_odds_game_betting_split import NbaOddsGameBettingSplit  # noqa: E501
from sportsdata.nba_odds.rest import ApiException


class TestNbaOddsGameBettingSplit(unittest.TestCase):
    """NbaOddsGameBettingSplit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaOddsGameBettingSplit(self):
        """Test NbaOddsGameBettingSplit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_odds.models.nba_odds_game_betting_split.NbaOddsGameBettingSplit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
