# coding: utf-8

"""
    NBA v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_odds
from sportsdata.nba_odds.models.nba_odds_consensus_outcome import NbaOddsConsensusOutcome  # noqa: E501
from sportsdata.nba_odds.rest import ApiException


class TestNbaOddsConsensusOutcome(unittest.TestCase):
    """NbaOddsConsensusOutcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaOddsConsensusOutcome(self):
        """Test NbaOddsConsensusOutcome"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_odds.models.nba_odds_consensus_outcome.NbaOddsConsensusOutcome()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
