# coding: utf-8

"""
    NBA v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata.nba_odds
from sportsdata.nba_odds.models.nba_odds_betting_market_split import NbaOddsBettingMarketSplit  # noqa: E501
from sportsdata.nba_odds.rest import ApiException


class TestNbaOddsBettingMarketSplit(unittest.TestCase):
    """NbaOddsBettingMarketSplit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNbaOddsBettingMarketSplit(self):
        """Test NbaOddsBettingMarketSplit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata.nba_odds.models.nba_odds_betting_market_split.NbaOddsBettingMarketSplit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
