# coding: utf-8

"""
    CWBB v3 Scores

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CwbbScoresGame(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'game_id': 'int',
        'season': 'int',
        'season_type': 'int',
        'status': 'str',
        'day': 'str',
        'date_time': 'str',
        'away_team': 'str',
        'home_team': 'str',
        'away_team_id': 'int',
        'home_team_id': 'int',
        'away_team_score': 'int',
        'home_team_score': 'int',
        'updated': 'str',
        'period': 'str',
        'time_remaining_minutes': 'int',
        'time_remaining_seconds': 'int',
        'global_game_id': 'int',
        'global_away_team_id': 'int',
        'global_home_team_id': 'int',
        'periods': 'list[CwbbScoresPeriod]'
    }

    attribute_map = {
        'game_id': 'GameID',
        'season': 'Season',
        'season_type': 'SeasonType',
        'status': 'Status',
        'day': 'Day',
        'date_time': 'DateTime',
        'away_team': 'AwayTeam',
        'home_team': 'HomeTeam',
        'away_team_id': 'AwayTeamID',
        'home_team_id': 'HomeTeamID',
        'away_team_score': 'AwayTeamScore',
        'home_team_score': 'HomeTeamScore',
        'updated': 'Updated',
        'period': 'Period',
        'time_remaining_minutes': 'TimeRemainingMinutes',
        'time_remaining_seconds': 'TimeRemainingSeconds',
        'global_game_id': 'GlobalGameID',
        'global_away_team_id': 'GlobalAwayTeamID',
        'global_home_team_id': 'GlobalHomeTeamID',
        'periods': 'Periods'
    }

    def __init__(self, game_id=None, season=None, season_type=None, status=None, day=None, date_time=None, away_team=None, home_team=None, away_team_id=None, home_team_id=None, away_team_score=None, home_team_score=None, updated=None, period=None, time_remaining_minutes=None, time_remaining_seconds=None, global_game_id=None, global_away_team_id=None, global_home_team_id=None, periods=None):  # noqa: E501
        """CwbbScoresGame - a model defined in Swagger"""  # noqa: E501
        self._game_id = None
        self._season = None
        self._season_type = None
        self._status = None
        self._day = None
        self._date_time = None
        self._away_team = None
        self._home_team = None
        self._away_team_id = None
        self._home_team_id = None
        self._away_team_score = None
        self._home_team_score = None
        self._updated = None
        self._period = None
        self._time_remaining_minutes = None
        self._time_remaining_seconds = None
        self._global_game_id = None
        self._global_away_team_id = None
        self._global_home_team_id = None
        self._periods = None
        self.discriminator = None
        if game_id is not None:
            self.game_id = game_id
        if season is not None:
            self.season = season
        if season_type is not None:
            self.season_type = season_type
        if status is not None:
            self.status = status
        if day is not None:
            self.day = day
        if date_time is not None:
            self.date_time = date_time
        if away_team is not None:
            self.away_team = away_team
        if home_team is not None:
            self.home_team = home_team
        if away_team_id is not None:
            self.away_team_id = away_team_id
        if home_team_id is not None:
            self.home_team_id = home_team_id
        if away_team_score is not None:
            self.away_team_score = away_team_score
        if home_team_score is not None:
            self.home_team_score = home_team_score
        if updated is not None:
            self.updated = updated
        if period is not None:
            self.period = period
        if time_remaining_minutes is not None:
            self.time_remaining_minutes = time_remaining_minutes
        if time_remaining_seconds is not None:
            self.time_remaining_seconds = time_remaining_seconds
        if global_game_id is not None:
            self.global_game_id = global_game_id
        if global_away_team_id is not None:
            self.global_away_team_id = global_away_team_id
        if global_home_team_id is not None:
            self.global_home_team_id = global_home_team_id
        if periods is not None:
            self.periods = periods

    @property
    def game_id(self):
        """Gets the game_id of this CwbbScoresGame.  # noqa: E501


        :return: The game_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._game_id

    @game_id.setter
    def game_id(self, game_id):
        """Sets the game_id of this CwbbScoresGame.


        :param game_id: The game_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._game_id = game_id

    @property
    def season(self):
        """Gets the season of this CwbbScoresGame.  # noqa: E501


        :return: The season of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._season

    @season.setter
    def season(self, season):
        """Sets the season of this CwbbScoresGame.


        :param season: The season of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._season = season

    @property
    def season_type(self):
        """Gets the season_type of this CwbbScoresGame.  # noqa: E501


        :return: The season_type of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._season_type

    @season_type.setter
    def season_type(self, season_type):
        """Sets the season_type of this CwbbScoresGame.


        :param season_type: The season_type of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._season_type = season_type

    @property
    def status(self):
        """Gets the status of this CwbbScoresGame.  # noqa: E501


        :return: The status of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CwbbScoresGame.


        :param status: The status of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def day(self):
        """Gets the day of this CwbbScoresGame.  # noqa: E501


        :return: The day of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day):
        """Sets the day of this CwbbScoresGame.


        :param day: The day of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._day = day

    @property
    def date_time(self):
        """Gets the date_time of this CwbbScoresGame.  # noqa: E501


        :return: The date_time of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._date_time

    @date_time.setter
    def date_time(self, date_time):
        """Sets the date_time of this CwbbScoresGame.


        :param date_time: The date_time of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._date_time = date_time

    @property
    def away_team(self):
        """Gets the away_team of this CwbbScoresGame.  # noqa: E501


        :return: The away_team of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._away_team

    @away_team.setter
    def away_team(self, away_team):
        """Sets the away_team of this CwbbScoresGame.


        :param away_team: The away_team of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._away_team = away_team

    @property
    def home_team(self):
        """Gets the home_team of this CwbbScoresGame.  # noqa: E501


        :return: The home_team of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._home_team

    @home_team.setter
    def home_team(self, home_team):
        """Sets the home_team of this CwbbScoresGame.


        :param home_team: The home_team of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._home_team = home_team

    @property
    def away_team_id(self):
        """Gets the away_team_id of this CwbbScoresGame.  # noqa: E501


        :return: The away_team_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._away_team_id

    @away_team_id.setter
    def away_team_id(self, away_team_id):
        """Sets the away_team_id of this CwbbScoresGame.


        :param away_team_id: The away_team_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._away_team_id = away_team_id

    @property
    def home_team_id(self):
        """Gets the home_team_id of this CwbbScoresGame.  # noqa: E501


        :return: The home_team_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._home_team_id

    @home_team_id.setter
    def home_team_id(self, home_team_id):
        """Sets the home_team_id of this CwbbScoresGame.


        :param home_team_id: The home_team_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._home_team_id = home_team_id

    @property
    def away_team_score(self):
        """Gets the away_team_score of this CwbbScoresGame.  # noqa: E501


        :return: The away_team_score of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._away_team_score

    @away_team_score.setter
    def away_team_score(self, away_team_score):
        """Sets the away_team_score of this CwbbScoresGame.


        :param away_team_score: The away_team_score of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._away_team_score = away_team_score

    @property
    def home_team_score(self):
        """Gets the home_team_score of this CwbbScoresGame.  # noqa: E501


        :return: The home_team_score of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._home_team_score

    @home_team_score.setter
    def home_team_score(self, home_team_score):
        """Sets the home_team_score of this CwbbScoresGame.


        :param home_team_score: The home_team_score of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._home_team_score = home_team_score

    @property
    def updated(self):
        """Gets the updated of this CwbbScoresGame.  # noqa: E501


        :return: The updated of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this CwbbScoresGame.


        :param updated: The updated of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def period(self):
        """Gets the period of this CwbbScoresGame.  # noqa: E501


        :return: The period of this CwbbScoresGame.  # noqa: E501
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this CwbbScoresGame.


        :param period: The period of this CwbbScoresGame.  # noqa: E501
        :type: str
        """

        self._period = period

    @property
    def time_remaining_minutes(self):
        """Gets the time_remaining_minutes of this CwbbScoresGame.  # noqa: E501


        :return: The time_remaining_minutes of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._time_remaining_minutes

    @time_remaining_minutes.setter
    def time_remaining_minutes(self, time_remaining_minutes):
        """Sets the time_remaining_minutes of this CwbbScoresGame.


        :param time_remaining_minutes: The time_remaining_minutes of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._time_remaining_minutes = time_remaining_minutes

    @property
    def time_remaining_seconds(self):
        """Gets the time_remaining_seconds of this CwbbScoresGame.  # noqa: E501


        :return: The time_remaining_seconds of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._time_remaining_seconds

    @time_remaining_seconds.setter
    def time_remaining_seconds(self, time_remaining_seconds):
        """Sets the time_remaining_seconds of this CwbbScoresGame.


        :param time_remaining_seconds: The time_remaining_seconds of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._time_remaining_seconds = time_remaining_seconds

    @property
    def global_game_id(self):
        """Gets the global_game_id of this CwbbScoresGame.  # noqa: E501


        :return: The global_game_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._global_game_id

    @global_game_id.setter
    def global_game_id(self, global_game_id):
        """Sets the global_game_id of this CwbbScoresGame.


        :param global_game_id: The global_game_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._global_game_id = global_game_id

    @property
    def global_away_team_id(self):
        """Gets the global_away_team_id of this CwbbScoresGame.  # noqa: E501


        :return: The global_away_team_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._global_away_team_id

    @global_away_team_id.setter
    def global_away_team_id(self, global_away_team_id):
        """Sets the global_away_team_id of this CwbbScoresGame.


        :param global_away_team_id: The global_away_team_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._global_away_team_id = global_away_team_id

    @property
    def global_home_team_id(self):
        """Gets the global_home_team_id of this CwbbScoresGame.  # noqa: E501


        :return: The global_home_team_id of this CwbbScoresGame.  # noqa: E501
        :rtype: int
        """
        return self._global_home_team_id

    @global_home_team_id.setter
    def global_home_team_id(self, global_home_team_id):
        """Sets the global_home_team_id of this CwbbScoresGame.


        :param global_home_team_id: The global_home_team_id of this CwbbScoresGame.  # noqa: E501
        :type: int
        """

        self._global_home_team_id = global_home_team_id

    @property
    def periods(self):
        """Gets the periods of this CwbbScoresGame.  # noqa: E501


        :return: The periods of this CwbbScoresGame.  # noqa: E501
        :rtype: list[CwbbScoresPeriod]
        """
        return self._periods

    @periods.setter
    def periods(self, periods):
        """Sets the periods of this CwbbScoresGame.


        :param periods: The periods of this CwbbScoresGame.  # noqa: E501
        :type: list[CwbbScoresPeriod]
        """

        self._periods = periods

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CwbbScoresGame, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CwbbScoresGame):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
