# coding: utf-8

# flake8: noqa
"""
    Soccer v3 Projections

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from sportsdata.soccer_projections.models.soccer_projections_dfs_slate import SoccerProjectionsDfsSlate
from sportsdata.soccer_projections.models.soccer_projections_dfs_slate_game import SoccerProjectionsDfsSlateGame
from sportsdata.soccer_projections.models.soccer_projections_dfs_slate_player import SoccerProjectionsDfsSlatePlayer
from sportsdata.soccer_projections.models.soccer_projections_game import SoccerProjectionsGame
from sportsdata.soccer_projections.models.soccer_projections_player_game_projection import SoccerProjectionsPlayerGameProjection
from sportsdata.soccer_projections.models.soccer_projections_playoff_aggregate_score import SoccerProjectionsPlayoffAggregateScore
