# coding: utf-8

"""
    NHL v3 Projections

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NhlProjectionsDfsSlatePlayer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'slate_player_id': 'int',
        'slate_id': 'int',
        'slate_game_id': 'int',
        'player_id': 'int',
        'player_game_projection_stat_id': 'int',
        'operator_player_id': 'str',
        'operator_slate_player_id': 'str',
        'operator_player_name': 'str',
        'operator_position': 'str',
        'operator_salary': 'int',
        'operator_roster_slots': 'list[str]',
        'removed_by_operator': 'bool',
        'team': 'str',
        'team_id': 'int'
    }

    attribute_map = {
        'slate_player_id': 'SlatePlayerID',
        'slate_id': 'SlateID',
        'slate_game_id': 'SlateGameID',
        'player_id': 'PlayerID',
        'player_game_projection_stat_id': 'PlayerGameProjectionStatID',
        'operator_player_id': 'OperatorPlayerID',
        'operator_slate_player_id': 'OperatorSlatePlayerID',
        'operator_player_name': 'OperatorPlayerName',
        'operator_position': 'OperatorPosition',
        'operator_salary': 'OperatorSalary',
        'operator_roster_slots': 'OperatorRosterSlots',
        'removed_by_operator': 'RemovedByOperator',
        'team': 'Team',
        'team_id': 'TeamID'
    }

    def __init__(self, slate_player_id=None, slate_id=None, slate_game_id=None, player_id=None, player_game_projection_stat_id=None, operator_player_id=None, operator_slate_player_id=None, operator_player_name=None, operator_position=None, operator_salary=None, operator_roster_slots=None, removed_by_operator=None, team=None, team_id=None):  # noqa: E501
        """NhlProjectionsDfsSlatePlayer - a model defined in Swagger"""  # noqa: E501
        self._slate_player_id = None
        self._slate_id = None
        self._slate_game_id = None
        self._player_id = None
        self._player_game_projection_stat_id = None
        self._operator_player_id = None
        self._operator_slate_player_id = None
        self._operator_player_name = None
        self._operator_position = None
        self._operator_salary = None
        self._operator_roster_slots = None
        self._removed_by_operator = None
        self._team = None
        self._team_id = None
        self.discriminator = None
        if slate_player_id is not None:
            self.slate_player_id = slate_player_id
        if slate_id is not None:
            self.slate_id = slate_id
        if slate_game_id is not None:
            self.slate_game_id = slate_game_id
        if player_id is not None:
            self.player_id = player_id
        if player_game_projection_stat_id is not None:
            self.player_game_projection_stat_id = player_game_projection_stat_id
        if operator_player_id is not None:
            self.operator_player_id = operator_player_id
        if operator_slate_player_id is not None:
            self.operator_slate_player_id = operator_slate_player_id
        if operator_player_name is not None:
            self.operator_player_name = operator_player_name
        if operator_position is not None:
            self.operator_position = operator_position
        if operator_salary is not None:
            self.operator_salary = operator_salary
        if operator_roster_slots is not None:
            self.operator_roster_slots = operator_roster_slots
        if removed_by_operator is not None:
            self.removed_by_operator = removed_by_operator
        if team is not None:
            self.team = team
        if team_id is not None:
            self.team_id = team_id

    @property
    def slate_player_id(self):
        """Gets the slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._slate_player_id

    @slate_player_id.setter
    def slate_player_id(self, slate_player_id):
        """Sets the slate_player_id of this NhlProjectionsDfsSlatePlayer.


        :param slate_player_id: The slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._slate_player_id = slate_player_id

    @property
    def slate_id(self):
        """Gets the slate_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The slate_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._slate_id

    @slate_id.setter
    def slate_id(self, slate_id):
        """Sets the slate_id of this NhlProjectionsDfsSlatePlayer.


        :param slate_id: The slate_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._slate_id = slate_id

    @property
    def slate_game_id(self):
        """Gets the slate_game_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The slate_game_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._slate_game_id

    @slate_game_id.setter
    def slate_game_id(self, slate_game_id):
        """Sets the slate_game_id of this NhlProjectionsDfsSlatePlayer.


        :param slate_game_id: The slate_game_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._slate_game_id = slate_game_id

    @property
    def player_id(self):
        """Gets the player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._player_id

    @player_id.setter
    def player_id(self, player_id):
        """Sets the player_id of this NhlProjectionsDfsSlatePlayer.


        :param player_id: The player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._player_id = player_id

    @property
    def player_game_projection_stat_id(self):
        """Gets the player_game_projection_stat_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The player_game_projection_stat_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._player_game_projection_stat_id

    @player_game_projection_stat_id.setter
    def player_game_projection_stat_id(self, player_game_projection_stat_id):
        """Sets the player_game_projection_stat_id of this NhlProjectionsDfsSlatePlayer.


        :param player_game_projection_stat_id: The player_game_projection_stat_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._player_game_projection_stat_id = player_game_projection_stat_id

    @property
    def operator_player_id(self):
        """Gets the operator_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: str
        """
        return self._operator_player_id

    @operator_player_id.setter
    def operator_player_id(self, operator_player_id):
        """Sets the operator_player_id of this NhlProjectionsDfsSlatePlayer.


        :param operator_player_id: The operator_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: str
        """

        self._operator_player_id = operator_player_id

    @property
    def operator_slate_player_id(self):
        """Gets the operator_slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: str
        """
        return self._operator_slate_player_id

    @operator_slate_player_id.setter
    def operator_slate_player_id(self, operator_slate_player_id):
        """Sets the operator_slate_player_id of this NhlProjectionsDfsSlatePlayer.


        :param operator_slate_player_id: The operator_slate_player_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: str
        """

        self._operator_slate_player_id = operator_slate_player_id

    @property
    def operator_player_name(self):
        """Gets the operator_player_name of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_player_name of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: str
        """
        return self._operator_player_name

    @operator_player_name.setter
    def operator_player_name(self, operator_player_name):
        """Sets the operator_player_name of this NhlProjectionsDfsSlatePlayer.


        :param operator_player_name: The operator_player_name of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: str
        """

        self._operator_player_name = operator_player_name

    @property
    def operator_position(self):
        """Gets the operator_position of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_position of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: str
        """
        return self._operator_position

    @operator_position.setter
    def operator_position(self, operator_position):
        """Sets the operator_position of this NhlProjectionsDfsSlatePlayer.


        :param operator_position: The operator_position of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: str
        """

        self._operator_position = operator_position

    @property
    def operator_salary(self):
        """Gets the operator_salary of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_salary of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._operator_salary

    @operator_salary.setter
    def operator_salary(self, operator_salary):
        """Sets the operator_salary of this NhlProjectionsDfsSlatePlayer.


        :param operator_salary: The operator_salary of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._operator_salary = operator_salary

    @property
    def operator_roster_slots(self):
        """Gets the operator_roster_slots of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The operator_roster_slots of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: list[str]
        """
        return self._operator_roster_slots

    @operator_roster_slots.setter
    def operator_roster_slots(self, operator_roster_slots):
        """Sets the operator_roster_slots of this NhlProjectionsDfsSlatePlayer.


        :param operator_roster_slots: The operator_roster_slots of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: list[str]
        """

        self._operator_roster_slots = operator_roster_slots

    @property
    def removed_by_operator(self):
        """Gets the removed_by_operator of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The removed_by_operator of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: bool
        """
        return self._removed_by_operator

    @removed_by_operator.setter
    def removed_by_operator(self, removed_by_operator):
        """Sets the removed_by_operator of this NhlProjectionsDfsSlatePlayer.


        :param removed_by_operator: The removed_by_operator of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: bool
        """

        self._removed_by_operator = removed_by_operator

    @property
    def team(self):
        """Gets the team of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The team of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this NhlProjectionsDfsSlatePlayer.


        :param team: The team of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: str
        """

        self._team = team

    @property
    def team_id(self):
        """Gets the team_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501


        :return: The team_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :rtype: int
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this NhlProjectionsDfsSlatePlayer.


        :param team_id: The team_id of this NhlProjectionsDfsSlatePlayer.  # noqa: E501
        :type: int
        """

        self._team_id = team_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NhlProjectionsDfsSlatePlayer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NhlProjectionsDfsSlatePlayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
