# coding: utf-8

# flake8: noqa

"""
    CFB v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from sportsdata.cfb_odds.cfb_odds.default_api import DefaultApi
# import ApiClient
from sportsdata.cfb_odds.api_client import ApiClient
from sportsdata.cfb_odds.configuration import Configuration
# import models into sdk package
from sportsdata.cfb_odds.models.cfb_odds_betting_entity_metadata import CfbOddsBettingEntityMetadata
from sportsdata.cfb_odds.models.cfb_odds_betting_event import CfbOddsBettingEvent
from sportsdata.cfb_odds.models.cfb_odds_betting_market import CfbOddsBettingMarket
from sportsdata.cfb_odds.models.cfb_odds_betting_market_result import CfbOddsBettingMarketResult
from sportsdata.cfb_odds.models.cfb_odds_betting_market_split import CfbOddsBettingMarketSplit
from sportsdata.cfb_odds.models.cfb_odds_betting_outcome import CfbOddsBettingOutcome
from sportsdata.cfb_odds.models.cfb_odds_betting_outcome_result import CfbOddsBettingOutcomeResult
from sportsdata.cfb_odds.models.cfb_odds_betting_split import CfbOddsBettingSplit
from sportsdata.cfb_odds.models.cfb_odds_consensus_outcome import CfbOddsConsensusOutcome
from sportsdata.cfb_odds.models.cfb_odds_game import CfbOddsGame
from sportsdata.cfb_odds.models.cfb_odds_game_betting_split import CfbOddsGameBettingSplit
from sportsdata.cfb_odds.models.cfb_odds_game_info import CfbOddsGameInfo
from sportsdata.cfb_odds.models.cfb_odds_game_odd import CfbOddsGameOdd
from sportsdata.cfb_odds.models.cfb_odds_matchup_trends import CfbOddsMatchupTrends
from sportsdata.cfb_odds.models.cfb_odds_period import CfbOddsPeriod
from sportsdata.cfb_odds.models.cfb_odds_sportsbook import CfbOddsSportsbook
from sportsdata.cfb_odds.models.cfb_odds_stadium import CfbOddsStadium
from sportsdata.cfb_odds.models.cfb_odds_team_game_trends import CfbOddsTeamGameTrends
from sportsdata.cfb_odds.models.cfb_odds_team_trends import CfbOddsTeamTrends
